# -*- coding: utf-8 -*-
"""test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LdGmBSBnDp9NxZAS-_68H1Q4lQYwJNO
"""

import joblib
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
def test_model_accuracy():
  model = joblib.load("model.pkl")
  iris = load_iris()
  X = iris.data
  y = iris.target
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
  predictions = model.predict(X_test)
  acc = accuracy_score(y_test, predictions)
  assert acc > 0.9, "Accuracy below 0.9"
  print("Test passed. Accuracy:", acc)